flutter-engine: Add 0005-dart-enable-mallinfo2.patch
Prevent this failure:

FAILED: obj/third_party/dart/runtime/vm/libdart_vm_jit.malloc_hooks_unsupported.o
/tmp/tmp-root.tmp/mnt/dev/disk/by-label/data/local/volatile/home/rzr/tmp/2022/2022-03-18/home/rzr/oniroproject/build-oniro-linux-blueprint-flutter/tmp/work/core2-64-oniro-linux/flutter-engine-debug/git-r0/src/buildtools/linux-x64/clang/bin/clang++ -MD -MF obj/third_party/dart/runtime/vm/libdart_vm_jit.malloc_hooks_unsupported.o.d --target=x86_64-unknown-linux-gnu --sysroot /tmp/tmp-root.tmp/mnt/dev/disk/by-label/data/local/volatile/home/rzr/tmp/2022/2022-03-18/home/rzr/oniroproject/build-oniro-linux-blueprint-flutter/tmp/work/core2-64-oniro-linux/flutter-engine-debug/git-r0/recipe-sysroot -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DTARGET_ARCH_X64 -DDART_TARGET_OS_LINUX -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../../third_party/dart/runtime -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/dart/runtime/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -m64 -march=x86-64 -fPIC -pipe -pthread -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -fvisibility=hidden --sysroot=/tmp/tmp-root.tmp/mnt/dev/disk/by-label/data/local/volatile/home/rzr/tmp/2022/2022-03-18/home/rzr/oniroproject/build-oniro-linux-blueprint-flutter/tmp/work/core2-64-oniro-linux/flutter-engine-debug/git-r0/recipe-sysroot -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions -c ../../third_party/dart/runtime/vm/malloc_hooks_unsupported.cc -o obj/third_party/dart/runtime/vm/libdart_vm_jit.malloc_hooks_unsupported.o
../../third_party/dart/runtime/vm/malloc_hooks_unsupported.cc:76:26: error: 'mallinfo' is deprecated [-Werror,-Wdeprecated-declarations]
  struct mallinfo info = mallinfo();
                         ^

Signed-off-by: Philippe Coval <philippe.coval@huawei.com>